# Generated by Django 3.2.4 on 2021-06-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences_count', models.FloatField()),
                ('characters_count', models.FloatField()),
                ('repeated_letters_count', models.FloatField()),
                ('spaces_count', models.FloatField()),
                ('chars_excl_spaces_count', models.FloatField()),
                ('repeated_spaces_count', models.FloatField()),
                ('whitespaces_count', models.FloatField()),
                ('chars_excl_whitespaces_count', models.FloatField()),
                ('repeated_whitespaces_count', models.FloatField()),
                ('count_words', models.FloatField()),
                ('duplicates_count', models.FloatField()),
                ('emoji_count', models.FloatField()),
                ('repeated_digits_count', models.FloatField()),
                ('whole_numbers_count', models.FloatField()),
                ('alpha_numeric_count', models.FloatField()),
                ('non_alpha_numeric_count', models.FloatField()),
                ('punctuations_count', models.FloatField()),
                ('repeated_punctuations_count', models.FloatField()),
                ('stop_words_count', models.FloatField()),
                ('dates_count', models.FloatField()),
                ('noun_phase_count', models.FloatField()),
                ('english_characters_count', models.FloatField()),
                ('non_english_characters_count', models.FloatField()),
                ('sentiment_polarity_score', models.FloatField()),
                ('sentiment_subjectivity_score', models.FloatField()),
                ('grammar_check_score', models.FloatField()),
                ('spelling_quality_score', models.FloatField()),
                ('ease_of_reading_score', models.FloatField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message')),
            ],
        ),
    ]
